### PR TITLE
Changes to index.html

### PR DESCRIPTION
**Pull request by eabedrapo**
* Bootstrap, moment.js and jQuery libraries from CDN (fallback to local for jquery and bootstrap. Ref: http://stackoverflow.com/questions/26192897/should-i-use-bootstrap-from-cdn-or-make-a-copy-on-my-server).
* Better navigation: dropdown for external links and languages.
* Left and right columns phone friendly.

### CODE REVIEW

**Comment by rorduno** [comment]
@eabedrapo was this coded directly on master?

**Comment by eabedrapo** [comment]
Hi @rorduno, yep in my repo and from there I sent a pull request to the main repo. This is the way I learned to work with my team at work, but if you guys think it's better to work in a branch next time I'll do.

**Comment by rorduno** [comment]
@eabedrapo whichever works for you, I was trying to run the code locally thats why I asked 😄

**Comment by eabedrapo** [comment]
Ha. Gotcha :smile: Any feedback will be very welcomed... or we can talk tomorrow at La Catrina :wink:

**Pull request merged**
